const INVALID_EMAIL = "INVALID_EMAIL"
const EMPTY_EMAIL = "EMPTY_EMAIL"
const EMPTY_PASSWORD = "EMPTY_PASSWORD"
const EMPTY_USERNAME = "EMPTY_USERNAME"
const EMPTY_CONFIRM_PASSWORD = "EMPTY_CONFIRM_PASSWORD"
const PASSWORD_DOES_NOT_MATCH = "PASSWORD_DOES_NOT_MATCH"

//  Panel.js
const IMAGE_SIZE = "1.5rem"

//  authentication.js
const JWT_TOKEN_LOCAL_STORAGE = "JWT_TOKEN_LOCAL_STORAGE"
const AUTH_STATE = "AUTH_STATE"

export {
  INVALID_EMAIL,
  EMPTY_EMAIL,
  EMPTY_PASSWORD,
  EMPTY_USERNAME,
  EMPTY_CONFIRM_PASSWORD,
  PASSWORD_DOES_NOT_MATCH,
  IMAGE_SIZE,
  JWT_TOKEN_LOCAL_STORAGE,
  AUTH_STATE
}
