const INVALID_EMAIL = "INVALID_EMAIL"
const EMPTY_EMAIL = "EMPTY_EMAIL"
const EMPTY_PASSWORD = "EMPTY_PASSWORD"
const EMPTY_USERNAME = "EMPTY_USERNAME"
const EMPTY_CONFIRM_PASSWORD = "EMPTY_CONFIRM_PASSWORD"
const PASSWORD_DOES_NOT_MATCH = "PASSWORD_DOES_NOT_MATCH"


export {INVALID_EMAIL, EMPTY_EMAIL, EMPTY_PASSWORD, EMPTY_USERNAME, EMPTY_CONFIRM_PASSWORD, PASSWORD_DOES_NOT_MATCH}